name = ["Ash", "Akshay", "us", "aniket", "us"]
print(name)
name.append("1")
print(name)
name.extend("ASH")
print(name)
A = name.pop()
print(A)
name.sort()
print(name)
B = name.index("Ash")
print(B)
# name.remove()
name.insert(2, 12)
print(name)
C = name.count("us")
print(C)
name.reverse()
print(name)
D = name.copy()
print(D)
name.clear()
print(name)
